### ISSUE TITLE
Unable to get Patch to work to live update UI when Mutate

### ISSUE THREAD

**Issue by mingsterism** [jycouet/kitql#162]
Hi, 
I'm currently trying to update the store live after I mutate with a Create mutation. 
However, i'm unable to get the patch to work. 

After we run a mutation, should we pass in the result into patch? 

for example
```
<script context="module">
export async function load({url}) {
        await KQL_AllUsers.queryLoad({
            fetch,
            variables: {
                first: 10,
                offset: 1
            }
        })
        return {}
    }
</script>
<script>
$: allUsers = KQL_AllUsers.data.allUsers
const addUser = async () => {
    const {data} = await KQL_CreateUser.mutate( {variables: {name: "John Doe"})
   await KQL_AllUsers.patch( {allUsers: data})    # <<<<<<<<<<<< i'm not sure what to pass in here 
}
</script>

<div>
    {JSON.stringify(allUsers)}
   <button on:click={addUser}>ADD USER</button>
</div>
```

The above is a sample code implementation of what i'm currently doing. 
However, the data does not live update when I run the patch. 
I get no errors. 

Appreciate the help. 
thanks

**Comment by jycouet** [comment]
Hi, 
Thanks for reaching out.
Yes, this feature is not documented a lot because I was not fully happy about it. It has a lot of potential, but you have to write quite a bit of code manually to make it work (And when you start with fragments & typings it starts to be complicated.

In your case, I guess that you have a lot of users... and you want to add the new user to the list (First? Last?)
You will display 1 more user than the request you did on top with first 10, offset 1.
The idea was something like (I'm coding on github directly, it's just to give an idea): 
```ts
const addUser = async () => {
    const {data} = await KQL_CreateUser.mutate( {variables: {name: "John Doe"})
    const lUsers = [data.createUser, ...$KQL_AllUsers.data.allUsers]
   await KQL_AllUsers.patch( {allUsers: lUsers})    # <<<<<<<<<<<< it should have the type of data of AllUsers 
}
```

Finally, the best is maybe to wait for the new version that will come out where we tackle this feature in another way.
To know more follow: https://github.com/jycouet/kitql/discussions/156

I leave it open for now and wait for your answer & our new version

**Comment by mingsterism** [comment]
Still didnt manage to get it to work. 
Probably will wait for #156 
looking forward to it !!

**Comment by jycouet** [comment]
It took time, but it finally happened 🥳

Check out the [Announcement here](https://github.com/jycouet/kitql/discussions/156#discussioncomment-3080343)

---

Basically, now for an Optimistic UI you should do like 👇
```ts
const totalCount = starInfo.stargazers.totalCount;
await GQL_RemoveStar.mutate({
variables: { id },
  optimisticResponse: {
    removeStar: {
      starrable: {
	__typename: 'Repository',
	id,
	viewerHasStarred: false,
	stargazers: { totalCount: totalCount - 1 }
    }
  }
}
```

Enjoy 🎉
